apiVersion: v1
kind: Service
metadata:
  name: trips-service
spec:
  selector:
    app: trips-pods
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-deployment
  labels:
    app: trips-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trips-pods
  template:
    metadata:
      labels:
        app: trips-pods
    spec:
      containers:
      - name: trips-pods
        image: registrydfa9032.azurecr.io/tripinsights/trips:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          value: sqladmindFa9032
        - name: SQL_SERVER
          value: sqlserverdfa9032.database.windows.net
        - name: SQL_PASSWORD
          value: pN5lk9Af5
        - name: SQL_DBNAME
          value: mydrivingDB
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
