apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
spec:
  selector:
    app: userprofile-pods
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  labels:
    app: userprofile-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofile-pods
  template:
    metadata:
      labels:
        app: userprofile-pods
    spec:
      containers:
      - name: userprofile-pods
        image: zluacr.azurecr.io/tripinsights/userprofile:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          value: sqladmindFa9032
        - name: SQL_SERVER
          value: sqlserverdfa9032.database.windows.net
        - name: SQL_PASSWORD
          value: pN5lk9Af5
        - name: SQL_DBNAME
          value: mydrivingDB
